### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by 9il** [libmir/mir-random#34]
@n8sh Could you please tag the next v0.2.8 release, list changes since v0.2.5, and make announce in the forum?

**Comment by n8sh** [comment]
@9il Sure, there are three more potential changes I'd like to discuss before release:

- add xoroshiro128+ https://github.com/libmir/mir-random/pull/35
- change `rand!bool` to use a sign test instead of testing the lowest bit (I need to create pull request)
- for some generators whose highest bits have better statistical quality than their lowest bits, when converting to output of smaller bit sizes use the highest bits (I need to create pull request)

**Comment by n8sh** [comment]
https://github.com/libmir/mir-random/pull/36/commits/1e7595711061496523c38f65fbf3c6fb751dfbeb

**Comment by 9il** [comment]
LGTM, please wrap unittests with version to speed up user unittests

**Comment by n8sh** [comment]
Okay, time to tag.

**Comment by 9il** [comment]
Well done! Thanks!
